
spring:
  profiles:
    include: swagger
    active: dev
  application:
    name: admin
  jpa:
    show-sql: true
flood:
  async:
    core-pool-size: 2
server:
  port: 9000
management:
  endpoints:
    web:
      base-path: /actuator




