
spring:
  profiles:
    include: swagger
    active: dev
  application:
    name: admin
  jpa:
    show-sql: true
    open-in-view: false
flood:
  async:
    core-pool-size: 2
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
  
server:
  port: 9000
management:
  endpoints:
    web:
      base-path: /actuator


